<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        // Temporarily disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table to start fresh
        DB::table('cities')->truncate();

        // Insert all cities in a single query for efficiency
        DB::table('cities')->insert([
            ['id' => 3, 'name' => 'الرياض', 'slug' => 'Riyadh', 'state_id' => 1],
            ['id' => 24, 'name' => 'المجمعة', 'slug' => 'Al-Majmaah', 'state_id' => 1],
            ['id' => 138, 'name' => 'الافلاج', 'slug' => 'Al-Aflaj', 'state_id' => 1],
            ['id' => 270, 'name' => 'الزلفي', 'slug' => 'Az-Zulfi', 'state_id' => 1],
            ['id' => 294, 'name' => 'رماح', 'slug' => 'Rumah', 'state_id' => 1],
            ['id' => 306, 'name' => 'الغاط', 'slug' => 'Al-Ghat', 'state_id' => 1],
            ['id' => 418, 'name' => 'عفيف', 'slug' => 'Afif', 'state_id' => 1],
            ['id' => 443, 'name' => 'ثادق', 'slug' => 'Thadiq', 'state_id' => 1],
            ['id' => 500, 'name' => 'شقراء', 'slug' => 'Shaqra', 'state_id' => 1],
            ['id' => 669, 'name' => 'الدوادمي', 'slug' => 'Ad-Duwadimi', 'state_id' => 1],
            ['id' => 795, 'name' => 'حريملاء', 'slug' => 'Huraymila', 'state_id' => 1],
            ['id' => 820, 'name' => 'مرات', 'slug' => 'Marat', 'state_id' => 1],
            ['id' => 828, 'name' => 'الدرعية', 'slug' => 'Ad-Diriyah', 'state_id' => 1],
            ['id' => 839, 'name' => 'ضرما', 'slug' => 'Duruma', 'state_id' => 1],
            ['id' => 880, 'name' => 'القويعية', 'slug' => 'Al-Quwayiyah', 'state_id' => 1],
            ['id' => 962, 'name' => 'الرين', 'slug' => 'Ar-Rayn', 'state_id' => 1],
            ['id' => 990, 'name' => 'المزاحمية', 'slug' => 'Al-Muzahimiyah', 'state_id' => 1],
            ['id' => 1061, 'name' => 'الخرج', 'slug' => 'Al-Kharj', 'state_id' => 1],
            ['id' => 1073, 'name' => 'الدلم', 'slug' => 'Ad-Dilam', 'state_id' => 1],
            ['id' => 1351, 'name' => 'وادي الدواسر', 'slug' => 'Wadi-Ad Dawasir', 'state_id' => 1],
            ['id' => 1361, 'name' => 'السليل', 'slug' => 'As-Sulayyil', 'state_id' => 1],
            ['id' => 3158, 'name' => 'الحريق', 'slug' => 'Al-Hariq', 'state_id' => 1],
            ['id' => 3161, 'name' => 'حوطة بني تميم', 'slug' => 'Hawtat-Bani Tamim', 'state_id' => 1],
            ['id' => 5, 'name' => 'الطائف', 'slug' => 'At-Taif', 'state_id' => 2],
            ['id' => 6, 'name' => 'مكة المكرمة', 'slug' => 'Makkah', 'state_id' => 2],
            ['id' => 18, 'name' => 'جدة', 'slug' => 'Jeddah', 'state_id' => 2],
            ['id' => 377, 'name' => 'رابغ', 'slug' => 'Rabigh', 'state_id' => 2],
            ['id' => 1105, 'name' => 'خليص', 'slug' => 'Khulays', 'state_id' => 2],
            ['id' => 1150, 'name' => 'الكامل', 'slug' => 'Al-Kamil', 'state_id' => 2],
            ['id' => 1248, 'name' => 'الخرمة', 'slug' => 'Al-Khurmah', 'state_id' => 2],
            ['id' => 1257, 'name' => 'الجموم', 'slug' => 'Al-Jumum', 'state_id' => 2],
            ['id' => 1390, 'name' => 'الليث', 'slug' => 'Al-Lith', 'state_id' => 2],
            ['id' => 1625, 'name' => 'القنفذة', 'slug' => 'Al-Qunfidhah', 'state_id' => 2],
            ['id' => 1905, 'name' => 'المويه القديم', 'slug' => 'Al-Muwayh Al Qadim', 'state_id' => 2],
            ['id' => 1906, 'name' => 'البحرة', 'slug' => 'Al-Baharah', 'state_id' => 2],
            ['id' => 2044, 'name' => 'المويه الجديد', 'slug' => 'Al-Muwayh Al Jadid', 'state_id' => 2],
            ['id' => 2129, 'name' => 'ميسان', 'slug' => 'Maysan', 'state_id' => 2],
            ['id' => 2156, 'name' => 'تربه', 'slug' => 'Turbah', 'state_id' => 2],
            ['id' => 2800, 'name' => 'رنية', 'slug' => 'Ranyah', 'state_id' => 2],
            ['id' => 3684, 'name' => 'اضم', 'slug' => 'Adham', 'state_id' => 2],
            ['id' => 23641, 'name' => 'العرضيات', 'slug' => 'Al-Ardhiyat', 'state_id' => 2],
            ['id' => 14, 'name' => 'المدينة المنورة', 'slug' => 'Madinah', 'state_id' => 3],
            ['id' => 199, 'name' => 'العلا', 'slug' => 'Al-Ula', 'state_id' => 3],
            ['id' => 288, 'name' => 'خيبر', 'slug' => 'Khaybar', 'state_id' => 3],
            ['id' => 360, 'name' => 'مهد الذهب', 'slug' => 'Mahd-Adh Dhahab', 'state_id' => 3],
            ['id' => 483, 'name' => 'ينبع', 'slug' => 'Yanbu', 'state_id' => 3],
            ['id' => 485, 'name' => 'العيص', 'slug' => 'Al-Is', 'state_id' => 3],
            ['id' => 777, 'name' => 'الحناكية', 'slug' => 'Al-Hinakiyah', 'state_id' => 3],
            ['id' => 1053, 'name' => 'بدر', 'slug' => 'Badr', 'state_id' => 3],
            ['id' => 11, 'name' => 'بريدة', 'slug' => 'Buraidah', 'state_id' => 4],
            ['id' => 80, 'name' => 'عنيزة', 'slug' => 'Unayzah', 'state_id' => 4],
            ['id' => 1986, 'name' => 'الاسياح', 'slug' => 'Al-Asyah', 'state_id' => 4],
            ['id' => 1999, 'name' => 'عيون الجواء', 'slug' => 'Uyun-Al Jawa', 'state_id' => 4],
            ['id' => 2448, 'name' => 'المذنب', 'slug' => 'Al-Midhnab', 'state_id' => 4],
            ['id' => 2467, 'name' => 'رياض الخبراء', 'slug' => 'Riyad-Al Khabra', 'state_id' => 4],
            ['id' => 2481, 'name' => 'البدائع', 'slug' => 'Al-Badai', 'state_id' => 4],
            ['id' => 2630, 'name' => 'البكيرية', 'slug' => 'Al-Bukayriyah', 'state_id' => 4],
            ['id' => 2777, 'name' => 'الشماسية', 'slug' => 'Ash-Shimasiyah', 'state_id' => 4],
            ['id' => 2988, 'name' => 'عقلة الصقور', 'slug' => 'Uqlat-As Suqur', 'state_id' => 4],
            ['id' => 3030, 'name' => 'النبهانية', 'slug' => 'An-Nabhaniyah', 'state_id' => 4],
            ['id' => 3151, 'name' => 'ضرية', 'slug' => 'Dariyah', 'state_id' => 4],
            ['id' => 13, 'name' => 'الدمام', 'slug' => 'Dammam', 'state_id' => 5],
            ['id' => 31, 'name' => 'الخبر', 'slug' => 'Al-Khobar', 'state_id' => 5],
            ['id' => 47, 'name' => 'حفر الباطن', 'slug' => 'Hafar-Al Batin', 'state_id' => 5],
            ['id' => 67, 'name' => 'القطيف', 'slug' => 'Al-Qatif', 'state_id' => 5],
            ['id' => 89, 'name' => 'قرية العليا', 'slug' => 'Qaryat-Al Ulya', 'state_id' => 5],
            ['id' => 113, 'name' => 'الجبيل', 'slug' => 'Al-Jubail', 'state_id' => 5],
            ['id' => 115, 'name' => 'النعيرية', 'slug' => 'An-Nuayriyah', 'state_id' => 5],
            ['id' => 243, 'name' => 'بقيق', 'slug' => 'Buqayq', 'state_id' => 5],
            ['id' => 2023, 'name' => 'العديد', 'slug' => 'Al-Adid', 'state_id' => 5],
            ['id' => 2464, 'name' => 'الخفجي', 'slug' => 'Al-Khafji', 'state_id' => 5],
            ['id' => 2590, 'name' => 'راس تنورة', 'slug' => 'Ras-Tannurah', 'state_id' => 5],
            ['id' => 3677, 'name' => 'الاحساء', 'slug' => 'Al-Ahsa', 'state_id' => 5],
            ['id' => 15, 'name' => 'ابها', 'slug' => 'Abha', 'state_id' => 6],
            ['id' => 62, 'name' => 'خميس مشيط', 'slug' => 'Khamis-Mushayt', 'state_id' => 6],
            ['id' => 65, 'name' => 'احد رفيده', 'slug' => 'Ahad-Rifaydah', 'state_id' => 6],
            ['id' => 256, 'name' => 'طريب', 'slug' => 'Tarib', 'state_id' => 6],
            ['id' => 1294, 'name' => 'المجاردة', 'slug' => 'Al-Majardah', 'state_id' => 6],
            ['id' => 1297, 'name' => 'بارق', 'slug' => 'Bariq', 'state_id' => 6],
            ['id' => 1443, 'name' => 'تثليث', 'slug' => 'Tathlith', 'state_id' => 6],
            ['id' => 1453, 'name' => 'الامواه', 'slug' => 'Al-Amwah', 'state_id' => 6],
            ['id' => 1514, 'name' => 'بيشة', 'slug' => 'Bishah', 'state_id' => 6],
            ['id' => 1626, 'name' => 'بلقرن', 'slug' => 'Balqarn', 'state_id' => 6],
            ['id' => 1801, 'name' => 'محايل', 'slug' => 'Muhayil', 'state_id' => 6],
            ['id' => 1846, 'name' => 'رجال المع', 'slug' => 'Rijal-Al Ma', 'state_id' => 6],
            ['id' => 2519, 'name' => 'النماص', 'slug' => 'An-Namas', 'state_id' => 6],
            ['id' => 2893, 'name' => 'البرك', 'slug' => 'Al-Birk', 'state_id' => 6],
            ['id' => 3273, 'name' => 'تنومة', 'slug' => 'Tanumah', 'state_id' => 6],
            ['id' => 3328, 'name' => 'سراة عبيدة', 'slug' => 'Sarat-Abidah', 'state_id' => 6],
            ['id' => 3381, 'name' => 'ظهران الجنوب', 'slug' => 'Dhahran-Al Janub', 'state_id' => 6],
            ['id' => 3383, 'name' => 'الحرجة', 'slug' => 'Al-Harajah', 'state_id' => 6],
            ['id' => 1, 'name' => 'تبوك', 'slug' => 'Tabuk', 'state_id' => 7],
            ['id' => 36, 'name' => 'حقل', 'slug' => 'Haql', 'state_id' => 7],
            ['id' => 74, 'name' => 'تيماء', 'slug' => 'Tayma', 'state_id' => 7],
            ['id' => 233, 'name' => 'الوجه', 'slug' => 'Al-Wajh', 'state_id' => 7],
            ['id' => 323, 'name' => 'املج', 'slug' => 'Umluj', 'state_id' => 7],
            ['id' => 1947, 'name' => 'ضبا', 'slug' => 'Duba', 'state_id' => 7],
            ['id' => 3614, 'name' => 'البدع', 'slug' => 'Al-Bada', 'state_id' => 7],
            ['id' => 10, 'name' => 'حائل', 'slug' => 'Hail', 'state_id' => 8],
            ['id' => 1228, 'name' => 'الشنان', 'slug' => 'Ash-Shinan', 'state_id' => 8],
            ['id' => 2332, 'name' => 'الشملي', 'slug' => 'Ash-Shamli', 'state_id' => 8],
            ['id' => 2351, 'name' => 'موقق', 'slug' => 'Mawqaq', 'state_id' => 8],
            ['id' => 2370, 'name' => 'بقعاء', 'slug' => 'Baqa', 'state_id' => 8],
            ['id' => 2602, 'name' => 'سميراء', 'slug' => 'Simira', 'state_id' => 8],
            ['id' => 2702, 'name' => 'السليمي', 'slug' => 'As-Sulaymi', 'state_id' => 8],
            ['id' => 2715, 'name' => 'الغزالة', 'slug' => 'Al-Ghazalah', 'state_id' => 8],
            ['id' => 2721, 'name' => 'الحائط', 'slug' => 'Al-Hait', 'state_id' => 8],
            ['id' => 2208, 'name' => 'طريف', 'slug' => 'Turaif', 'state_id' => 9],
            ['id' => 2213, 'name' => 'عرعر', 'slug' => 'Arar', 'state_id' => 9],
            ['id' => 2215, 'name' => 'العويقلية', 'slug' => 'Al-Uwayqiliyah', 'state_id' => 9],
            ['id' => 2256, 'name' => 'رفحاء', 'slug' => 'Rafha', 'state_id' => 9],
            ['id' => 17, 'name' => 'جازان', 'slug' => 'Jazan', 'state_id' => 10],
            ['id' => 3402, 'name' => 'الدرب', 'slug' => 'Ad-Darb', 'state_id' => 10],
            ['id' => 3427, 'name' => 'الريث', 'slug' => 'Ar-Rayth', 'state_id' => 10],
            ['id' => 3446, 'name' => 'فيفاء', 'slug' => 'Fayfa', 'state_id' => 10],
            ['id' => 3447, 'name' => 'الدائر', 'slug' => 'Ad-Dair', 'state_id' => 10],
            ['id' => 3455, 'name' => 'العيدابي', 'slug' => 'Al-Aydabi', 'state_id' => 10],
            ['id' => 3457, 'name' => 'هروب', 'slug' => 'Harub', 'state_id' => 10],
            ['id' => 3462, 'name' => 'بيش', 'slug' => 'Bish', 'state_id' => 10],
            ['id' => 3479, 'name' => 'صبيا', 'slug' => 'Sabya', 'state_id' => 10],
            ['id' => 3499, 'name' => 'ضمد', 'slug' => 'Damad', 'state_id' => 10],
            ['id' => 3525, 'name' => 'ابو عريش', 'slug' => 'Abu-Arish', 'state_id' => 10],
            ['id' => 3542, 'name' => 'صامطة', 'slug' => 'Samtah', 'state_id' => 10],
            ['id' => 3555, 'name' => 'الطوال', 'slug' => 'At-Tuwal', 'state_id' => 10],
            ['id' => 3571, 'name' => 'فرسان (منطقة جازان)', 'slug' => 'Farasan', 'state_id' => 10],
            ['id' => 3597, 'name' => 'العارضة', 'slug' => 'Al-Aridah', 'state_id' => 10],
            ['id' => 3652, 'name' => 'احد المسارحة', 'slug' => 'Ahad-Al Musarihah', 'state_id' => 10],
            ['id' => 18065, 'name' => 'الحرث', 'slug' => 'Al-Harf', 'state_id' => 10],
            ['id' => 2522, 'name' => 'يدمة', 'slug' => 'Yadamah', 'state_id' => 11],
            ['id' => 2877, 'name' => 'ثار', 'slug' => 'Thar', 'state_id' => 11],
            ['id' => 3342, 'name' => 'بدر الجنوب', 'slug' => 'Badr-Al Janub', 'state_id' => 11],
            ['id' => 3347, 'name' => 'شرورة', 'slug' => 'Sharurah', 'state_id' => 11],
            ['id' => 3389, 'name' => 'بئر خباش', 'slug' => 'Bir-Khubash', 'state_id' => 11],
            ['id' => 3396, 'name' => 'حبونا', 'slug' => 'Hubuna', 'state_id' => 11],
            ['id' => 3417, 'name' => 'نجران', 'slug' => 'Najran', 'state_id' => 11],
            ['id' => 1425, 'name' => 'الحجرة', 'slug' => 'Al-Hajrah', 'state_id' => 12],
            ['id' => 1465, 'name' => 'القرى', 'slug' => 'Al-Qara', 'state_id' => 12],
            ['id' => 1531, 'name' => 'بلجرشي', 'slug' => 'Biljurashi', 'state_id' => 12],
            ['id' => 1542, 'name' => 'الباحة', 'slug' => 'Bahah', 'state_id' => 12],
            ['id' => 1545, 'name' => 'بني حسن', 'slug' => 'Bani-Hasan', 'state_id' => 12],
            ['id' => 2819, 'name' => 'العقيق', 'slug' => 'Al-Aqiq', 'state_id' => 12],
            ['id' => 2835, 'name' => 'المندق', 'slug' => 'Al-Mandaq', 'state_id' => 12],
            ['id' => 3220, 'name' => 'قلوة', 'slug' => 'Qilwah', 'state_id' => 12],
            ['id' => 3235, 'name' => 'غامد الزناد', 'slug' => 'Ghamid-Az Zinad', 'state_id' => 12],
            ['id' => 3236, 'name' => 'المخواة', 'slug' => 'Al-Mukhwah', 'state_id' => 12],
            ['id' => 2226, 'name' => 'القريات', 'slug' => 'Al-Qurayyat', 'state_id' => 13],
            ['id' => 2237, 'name' => 'سكاكا', 'slug' => 'Sakaka', 'state_id' => 13],
            ['id' => 2240, 'name' => 'طبرجل', 'slug' => 'Tubarjal', 'state_id' => 13],
            ['id' => 2268, 'name' => 'دومة الجندل', 'slug' => 'Dawmat-Al Jandal', 'state_id' => 13],
            ['id' => 23696, 'name' => 'وادي الفرع', 'slug' => 'Wadi-Al Faraa', 'state_id' => 3],
        ]);

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}